#!/bin/sh

if mountpoint -q /target; then
  KERNEL_VERSION=$(uname -r)
  echo "Installing objects to /target/lib/modules/${KERNEL_VERSION}/"
  mkdir -p /target/lib/modules/${KERNEL_VERSION}/
  cp /vboxguest/amd64/src/vboxguest-${VBOX_VERSION}/*.ko /target/lib/modules/${KERNEL_VERSION}/
  echo "Installing mount.vboxsf to /target/sbin"
  mkdir -p /target/sbin/
  cp /vboxguest/amd64/lib/VBoxGuestAdditions/mount.vboxsf /target/sbin/
else
  echo "/target is not a mountpoint."
  echo "You can re-run this container with -v /usr/share/oem:/target"
fi
